version: '2'
services:
  dumpster:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9980
      unhealthy_threshold: 3
      initializing_timeout: 10000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 15000
